// flow-typed signature: 2089a61ab3b047cc302c52c9cae480a8
// flow-typed version: <<STUB>>/dayzed_v2.2.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dayzed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dayzed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dayzed/dist/dayzed.cjs' {
  declare module.exports: any;
}

declare module 'dayzed/dist/dayzed.esm' {
  declare module.exports: any;
}

declare module 'dayzed/dist/dayzed.umd' {
  declare module.exports: any;
}

declare module 'dayzed/dist/dayzed.umd.min' {
  declare module.exports: any;
}

declare module 'dayzed/preact/dist/dayzed.cjs' {
  declare module.exports: any;
}

declare module 'dayzed/preact/dist/dayzed.esm' {
  declare module.exports: any;
}

declare module 'dayzed/preact/dist/dayzed.umd' {
  declare module.exports: any;
}

declare module 'dayzed/preact/dist/dayzed.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dayzed/dist/dayzed.cjs.js' {
  declare module.exports: $Exports<'dayzed/dist/dayzed.cjs'>;
}
declare module 'dayzed/dist/dayzed.esm.js' {
  declare module.exports: $Exports<'dayzed/dist/dayzed.esm'>;
}
declare module 'dayzed/dist/dayzed.umd.js' {
  declare module.exports: $Exports<'dayzed/dist/dayzed.umd'>;
}
declare module 'dayzed/dist/dayzed.umd.min.js' {
  declare module.exports: $Exports<'dayzed/dist/dayzed.umd.min'>;
}
declare module 'dayzed/preact/dist/dayzed.cjs.js' {
  declare module.exports: $Exports<'dayzed/preact/dist/dayzed.cjs'>;
}
declare module 'dayzed/preact/dist/dayzed.esm.js' {
  declare module.exports: $Exports<'dayzed/preact/dist/dayzed.esm'>;
}
declare module 'dayzed/preact/dist/dayzed.umd.js' {
  declare module.exports: $Exports<'dayzed/preact/dist/dayzed.umd'>;
}
declare module 'dayzed/preact/dist/dayzed.umd.min.js' {
  declare module.exports: $Exports<'dayzed/preact/dist/dayzed.umd.min'>;
}
