// flow-typed signature: 3a5723f71ed754b253334d16ed5b113c
// flow-typed version: <<STUB>>/@kiwicom/orbit-components/lib/icons_v0.0.1/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kiwicom/orbit-components/lib/icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kiwicom/orbit-components/lib/icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kiwicom/orbit-components/lib/icons/Accommodation' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/AccountCircle' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/AirConditioning' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Airplane' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/AirplaneDown' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/AirplaneLanding' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/AirplaneOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/AirplaneReturn' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/AirplaneRight' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/AirplaneTakeoff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/AirplaneUp' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/AirportSecurity' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Alert' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/AlertCircle' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/All' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Anywhere' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ArrowDown' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ArrowUp' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Atm' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Attachment' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/BaggageCabin' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/BaggageCabinNone' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/BaggageChecked' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/BaggageNone' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/BaggagePersonalItem' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/BaggagePersonalItemNone' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/BaggageRecheck' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/BaggageSet' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/BaggageStorage' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/BillingDetails' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/BoardingGate' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Boat' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Bug' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Bus' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Calendar' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/CalendarAnytime' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/CalendarRange' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/CalendarTripLength' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Camera' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Car' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/CarDoor' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/CarRental' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Chart' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Chat' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Check' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/CheckCircle' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ChevronDown' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ChevronLeft' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ChevronRight' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ChevronUp' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Child' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ChildFriendly' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Circle' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/CircleEmpty' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/CircleFilled' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/CircleSmall' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/City' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Clock' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Close' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/CloseCircle' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Cocktail' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Code' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Coffee' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Compare' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Compass' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ContactEmail' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/CreditCard' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Deals' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/DeviceDesktop' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/DeviceMobile' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Document' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Download' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Duplicate' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Edit' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/EditOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Email' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Entertainment' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Exchange' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Facebook' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Feedback' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Filters' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/FlightDirect' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/FlightMulticity' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/FlightNomad' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/FlightReturn' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/FlightServices' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Fuel' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/FullScreen' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/FullScreenOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Gallery' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/GenderMan' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/GenderWoman' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Google' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Gps' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/GpsIos' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/GpsOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Grid' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Gym' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/History' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Infant' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/InformationCircle' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Instagram' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Insurance' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/InsuranceConfirmed' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/InsuranceOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Invoice' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ItemCompleted' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Kiwicom' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/KiwicomCare' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/KiwicomGuarantee' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Leisure' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Link' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Linkedin' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/List' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Loading' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Location' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationA' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationAdd' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationB' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationC' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationD' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationE' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationF' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationG' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationH' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationI' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationJ' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Lock' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LockOpen' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Logout' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Lounge' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Map' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Meal' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/MenuHamburger' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/MenuKebab' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/MenuMeatballs' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Messages' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/MessagesOutline' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Minus' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/MinusCircle' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Money' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/MoneyTransferIn' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/MoneyTransferOut' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Moon' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/MusicalInstruments' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/NewWindow' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Nonstop' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Notification' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/NotificationOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/NotificationOn' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/OnlineCheckin' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/OnlineCheckinOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Outlook' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Paid' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Parking' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Partners' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Passenger' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/PassengerAdd' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/PassengerOutline' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/PassengerRemove' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Passengers' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Passport' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Pet' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Pharmacy' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Phone' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Playground' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Plus' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/PlusCircle' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Pool' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/PowerPlug' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/PowerPlugOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/PriorityBoarding' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Profit' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/PromoCode' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/QuestionCircle' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/RadiusSearch' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Refund' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Relax' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Reload' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Remove' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Replace' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Restaurant' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/RouteNoStops' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/RouteOneStop' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/RouteTwoStops' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Search' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Seat' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Security' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/SelfTransfer' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Send' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Settings' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Share' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ShareAndroid' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ShareIos' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Shopping' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ShowLess' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ShowMore' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Sightseeing' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Smoking' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/SmokingOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Sort' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Spa' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/SportEquipment' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Sports' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/StarEmpty' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/StarFull' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Subway' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Suitcase' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Sun' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Sunrise' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Taxi' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/TermsAndConditions' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ThumbDown' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ThumbUp' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Ticket' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/TicketFlight' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/TicketOutline' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/TicketTrain' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Timelapse' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Timer' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Tips' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Toilets' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Train' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Transmission' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Trip' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Twitter' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Uber' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Upload' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Visa' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Visibility' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/VisibilityOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Walk' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Wallet' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Wheelchair' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Wifi' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/WifiOff' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kiwicom/orbit-components/lib/icons/Accommodation.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Accommodation'>;
}
declare module '@kiwicom/orbit-components/lib/icons/AccountCircle.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/AccountCircle'>;
}
declare module '@kiwicom/orbit-components/lib/icons/AirConditioning.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/AirConditioning'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Airplane.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Airplane'>;
}
declare module '@kiwicom/orbit-components/lib/icons/AirplaneDown.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/AirplaneDown'>;
}
declare module '@kiwicom/orbit-components/lib/icons/AirplaneLanding.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/AirplaneLanding'>;
}
declare module '@kiwicom/orbit-components/lib/icons/AirplaneOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/AirplaneOff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/AirplaneReturn.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/AirplaneReturn'>;
}
declare module '@kiwicom/orbit-components/lib/icons/AirplaneRight.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/AirplaneRight'>;
}
declare module '@kiwicom/orbit-components/lib/icons/AirplaneTakeoff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/AirplaneTakeoff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/AirplaneUp.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/AirplaneUp'>;
}
declare module '@kiwicom/orbit-components/lib/icons/AirportSecurity.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/AirportSecurity'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Alert.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Alert'>;
}
declare module '@kiwicom/orbit-components/lib/icons/AlertCircle.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/AlertCircle'>;
}
declare module '@kiwicom/orbit-components/lib/icons/All.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/All'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Anywhere.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Anywhere'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ArrowDown.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ArrowDown'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ArrowUp.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ArrowUp'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Atm.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Atm'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Attachment.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Attachment'>;
}
declare module '@kiwicom/orbit-components/lib/icons/BaggageCabin.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/BaggageCabin'>;
}
declare module '@kiwicom/orbit-components/lib/icons/BaggageCabinNone.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/BaggageCabinNone'>;
}
declare module '@kiwicom/orbit-components/lib/icons/BaggageChecked.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/BaggageChecked'>;
}
declare module '@kiwicom/orbit-components/lib/icons/BaggageNone.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/BaggageNone'>;
}
declare module '@kiwicom/orbit-components/lib/icons/BaggagePersonalItem.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/BaggagePersonalItem'>;
}
declare module '@kiwicom/orbit-components/lib/icons/BaggagePersonalItemNone.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/BaggagePersonalItemNone'>;
}
declare module '@kiwicom/orbit-components/lib/icons/BaggageRecheck.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/BaggageRecheck'>;
}
declare module '@kiwicom/orbit-components/lib/icons/BaggageSet.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/BaggageSet'>;
}
declare module '@kiwicom/orbit-components/lib/icons/BaggageStorage.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/BaggageStorage'>;
}
declare module '@kiwicom/orbit-components/lib/icons/BillingDetails.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/BillingDetails'>;
}
declare module '@kiwicom/orbit-components/lib/icons/BoardingGate.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/BoardingGate'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Boat.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Boat'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Bug.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Bug'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Bus.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Bus'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Calendar.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Calendar'>;
}
declare module '@kiwicom/orbit-components/lib/icons/CalendarAnytime.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/CalendarAnytime'>;
}
declare module '@kiwicom/orbit-components/lib/icons/CalendarRange.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/CalendarRange'>;
}
declare module '@kiwicom/orbit-components/lib/icons/CalendarTripLength.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/CalendarTripLength'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Camera.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Camera'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Car.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Car'>;
}
declare module '@kiwicom/orbit-components/lib/icons/CarDoor.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/CarDoor'>;
}
declare module '@kiwicom/orbit-components/lib/icons/CarRental.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/CarRental'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Chart.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Chart'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Chat.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Chat'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Check.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Check'>;
}
declare module '@kiwicom/orbit-components/lib/icons/CheckCircle.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/CheckCircle'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ChevronDown.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ChevronDown'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ChevronLeft.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ChevronLeft'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ChevronRight.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ChevronRight'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ChevronUp.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ChevronUp'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Child.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Child'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ChildFriendly.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ChildFriendly'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Circle.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Circle'>;
}
declare module '@kiwicom/orbit-components/lib/icons/CircleEmpty.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/CircleEmpty'>;
}
declare module '@kiwicom/orbit-components/lib/icons/CircleFilled.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/CircleFilled'>;
}
declare module '@kiwicom/orbit-components/lib/icons/CircleSmall.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/CircleSmall'>;
}
declare module '@kiwicom/orbit-components/lib/icons/City.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/City'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Clock.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Clock'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Close.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Close'>;
}
declare module '@kiwicom/orbit-components/lib/icons/CloseCircle.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/CloseCircle'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Cocktail.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Cocktail'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Code.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Code'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Coffee.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Coffee'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Compare.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Compare'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Compass.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Compass'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ContactEmail.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ContactEmail'>;
}
declare module '@kiwicom/orbit-components/lib/icons/CreditCard.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/CreditCard'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Deals.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Deals'>;
}
declare module '@kiwicom/orbit-components/lib/icons/DeviceDesktop.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/DeviceDesktop'>;
}
declare module '@kiwicom/orbit-components/lib/icons/DeviceMobile.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/DeviceMobile'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Document.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Document'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Download.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Download'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Duplicate.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Duplicate'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Edit.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Edit'>;
}
declare module '@kiwicom/orbit-components/lib/icons/EditOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/EditOff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Email.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Email'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Entertainment.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Entertainment'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Exchange.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Exchange'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Facebook.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Facebook'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Feedback.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Feedback'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Filters.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Filters'>;
}
declare module '@kiwicom/orbit-components/lib/icons/FlightDirect.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/FlightDirect'>;
}
declare module '@kiwicom/orbit-components/lib/icons/FlightMulticity.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/FlightMulticity'>;
}
declare module '@kiwicom/orbit-components/lib/icons/FlightNomad.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/FlightNomad'>;
}
declare module '@kiwicom/orbit-components/lib/icons/FlightReturn.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/FlightReturn'>;
}
declare module '@kiwicom/orbit-components/lib/icons/FlightServices.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/FlightServices'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Fuel.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Fuel'>;
}
declare module '@kiwicom/orbit-components/lib/icons/FullScreen.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/FullScreen'>;
}
declare module '@kiwicom/orbit-components/lib/icons/FullScreenOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/FullScreenOff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Gallery.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Gallery'>;
}
declare module '@kiwicom/orbit-components/lib/icons/GenderMan.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/GenderMan'>;
}
declare module '@kiwicom/orbit-components/lib/icons/GenderWoman.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/GenderWoman'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Google.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Google'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Gps.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Gps'>;
}
declare module '@kiwicom/orbit-components/lib/icons/GpsIos.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/GpsIos'>;
}
declare module '@kiwicom/orbit-components/lib/icons/GpsOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/GpsOff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Grid.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Grid'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Gym.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Gym'>;
}
declare module '@kiwicom/orbit-components/lib/icons/History.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/History'>;
}
declare module '@kiwicom/orbit-components/lib/icons/index' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons'>;
}
declare module '@kiwicom/orbit-components/lib/icons/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Infant.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Infant'>;
}
declare module '@kiwicom/orbit-components/lib/icons/InformationCircle.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/InformationCircle'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Instagram.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Instagram'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Insurance.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Insurance'>;
}
declare module '@kiwicom/orbit-components/lib/icons/InsuranceConfirmed.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/InsuranceConfirmed'>;
}
declare module '@kiwicom/orbit-components/lib/icons/InsuranceOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/InsuranceOff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Invoice.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Invoice'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ItemCompleted.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ItemCompleted'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Kiwicom.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Kiwicom'>;
}
declare module '@kiwicom/orbit-components/lib/icons/KiwicomCare.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/KiwicomCare'>;
}
declare module '@kiwicom/orbit-components/lib/icons/KiwicomGuarantee.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/KiwicomGuarantee'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Leisure.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Leisure'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Link.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Link'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Linkedin.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Linkedin'>;
}
declare module '@kiwicom/orbit-components/lib/icons/List.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/List'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Loading.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Loading'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Location.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Location'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationA.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationA'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationAdd.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationAdd'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationB.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationB'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationC.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationC'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationD.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationD'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationE.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationE'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationF.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationF'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationG.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationG'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationH.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationH'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationI.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationI'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationJ.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationJ'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Lock.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Lock'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LockOpen.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LockOpen'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Logout.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Logout'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Lounge.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Lounge'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Map.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Map'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Meal.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Meal'>;
}
declare module '@kiwicom/orbit-components/lib/icons/MenuHamburger.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/MenuHamburger'>;
}
declare module '@kiwicom/orbit-components/lib/icons/MenuKebab.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/MenuKebab'>;
}
declare module '@kiwicom/orbit-components/lib/icons/MenuMeatballs.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/MenuMeatballs'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Messages.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Messages'>;
}
declare module '@kiwicom/orbit-components/lib/icons/MessagesOutline.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/MessagesOutline'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Minus.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Minus'>;
}
declare module '@kiwicom/orbit-components/lib/icons/MinusCircle.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/MinusCircle'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Money.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Money'>;
}
declare module '@kiwicom/orbit-components/lib/icons/MoneyTransferIn.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/MoneyTransferIn'>;
}
declare module '@kiwicom/orbit-components/lib/icons/MoneyTransferOut.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/MoneyTransferOut'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Moon.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Moon'>;
}
declare module '@kiwicom/orbit-components/lib/icons/MusicalInstruments.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/MusicalInstruments'>;
}
declare module '@kiwicom/orbit-components/lib/icons/NewWindow.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/NewWindow'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Nonstop.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Nonstop'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Notification.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Notification'>;
}
declare module '@kiwicom/orbit-components/lib/icons/NotificationOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/NotificationOff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/NotificationOn.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/NotificationOn'>;
}
declare module '@kiwicom/orbit-components/lib/icons/OnlineCheckin.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/OnlineCheckin'>;
}
declare module '@kiwicom/orbit-components/lib/icons/OnlineCheckinOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/OnlineCheckinOff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Outlook.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Outlook'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Paid.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Paid'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Parking.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Parking'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Partners.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Partners'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Passenger.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Passenger'>;
}
declare module '@kiwicom/orbit-components/lib/icons/PassengerAdd.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/PassengerAdd'>;
}
declare module '@kiwicom/orbit-components/lib/icons/PassengerOutline.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/PassengerOutline'>;
}
declare module '@kiwicom/orbit-components/lib/icons/PassengerRemove.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/PassengerRemove'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Passengers.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Passengers'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Passport.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Passport'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Pet.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Pet'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Pharmacy.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Pharmacy'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Phone.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Phone'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Playground.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Playground'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Plus.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Plus'>;
}
declare module '@kiwicom/orbit-components/lib/icons/PlusCircle.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/PlusCircle'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Pool.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Pool'>;
}
declare module '@kiwicom/orbit-components/lib/icons/PowerPlug.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/PowerPlug'>;
}
declare module '@kiwicom/orbit-components/lib/icons/PowerPlugOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/PowerPlugOff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/PriorityBoarding.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/PriorityBoarding'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Profit.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Profit'>;
}
declare module '@kiwicom/orbit-components/lib/icons/PromoCode.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/PromoCode'>;
}
declare module '@kiwicom/orbit-components/lib/icons/QuestionCircle.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/QuestionCircle'>;
}
declare module '@kiwicom/orbit-components/lib/icons/RadiusSearch.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/RadiusSearch'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Refund.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Refund'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Relax.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Relax'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Reload.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Reload'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Remove.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Remove'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Replace.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Replace'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Restaurant.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Restaurant'>;
}
declare module '@kiwicom/orbit-components/lib/icons/RouteNoStops.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/RouteNoStops'>;
}
declare module '@kiwicom/orbit-components/lib/icons/RouteOneStop.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/RouteOneStop'>;
}
declare module '@kiwicom/orbit-components/lib/icons/RouteTwoStops.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/RouteTwoStops'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Search.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Search'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Seat.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Seat'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Security.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Security'>;
}
declare module '@kiwicom/orbit-components/lib/icons/SelfTransfer.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/SelfTransfer'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Send.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Send'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Settings.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Settings'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Share.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Share'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ShareAndroid.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ShareAndroid'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ShareIos.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ShareIos'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Shopping.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Shopping'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ShowLess.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ShowLess'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ShowMore.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ShowMore'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Sightseeing.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Sightseeing'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Smoking.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Smoking'>;
}
declare module '@kiwicom/orbit-components/lib/icons/SmokingOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/SmokingOff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Sort.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Sort'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Spa.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Spa'>;
}
declare module '@kiwicom/orbit-components/lib/icons/SportEquipment.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/SportEquipment'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Sports.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Sports'>;
}
declare module '@kiwicom/orbit-components/lib/icons/StarEmpty.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/StarEmpty'>;
}
declare module '@kiwicom/orbit-components/lib/icons/StarFull.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/StarFull'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Subway.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Subway'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Suitcase.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Suitcase'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Sun.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Sun'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Sunrise.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Sunrise'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Taxi.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Taxi'>;
}
declare module '@kiwicom/orbit-components/lib/icons/TermsAndConditions.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/TermsAndConditions'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ThumbDown.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ThumbDown'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ThumbUp.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ThumbUp'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Ticket.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Ticket'>;
}
declare module '@kiwicom/orbit-components/lib/icons/TicketFlight.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/TicketFlight'>;
}
declare module '@kiwicom/orbit-components/lib/icons/TicketOutline.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/TicketOutline'>;
}
declare module '@kiwicom/orbit-components/lib/icons/TicketTrain.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/TicketTrain'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Timelapse.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Timelapse'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Timer.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Timer'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Tips.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Tips'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Toilets.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Toilets'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Train.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Train'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Transmission.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Transmission'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Trip.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Trip'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Twitter.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Twitter'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Uber.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Uber'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Upload.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Upload'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Visa.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Visa'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Visibility.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Visibility'>;
}
declare module '@kiwicom/orbit-components/lib/icons/VisibilityOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/VisibilityOff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Walk.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Walk'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Wallet.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Wallet'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Wheelchair.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Wheelchair'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Wifi.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Wifi'>;
}
declare module '@kiwicom/orbit-components/lib/icons/WifiOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/WifiOff'>;
}
