version: 2 
jobs: 
  build:
    docker:
      - image: cypress/browsers:chrome67
    steps: 
      - checkout # special step to check out source code to working directory
      - run:
          name: install
          command: yarn
      - run: 
          name: lint
          command: yarn lint
      - run: 
          name: build
          command: yarn build
      - run: 
          name: e2eTest
          command: yarn cypress:run