version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn

      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Run all tests
          command: yarn test
