# https://weekend-api.now.sh/

query Interests($city: String!, $country: String!) {
  interests(city: $city, country: $country, interest: "drinks") {
    id
    img
    name
    category
    address
    coords {
      lat
      lon
    }
    score
    url
  }
}
