# https://weekend-api.now.sh/

query {
  interests(city: "Brno", country: "CZ", interest: "drinks") {
    id
    img
    name
    category
    address
    coords {
      lat
      lon
    }
    score
    url
  }
}
