# https://weekend-api.now.sh/

query Locations ($query: String!) {
  locations(query: $query, limit: 20) {
    id
    code
    name
    coords {
      lat
      lon
    }
    slug
    timezone
    type
    city {
      id
      name
      country
    }
  }
}
