query Search($params: SearchParams!) {
  search(params: $params) {
    price
    bookingToken
    route {
      from {
        city
        iata
        timeLocal
      }
      to {
        city
        iata
        timeLocal
      }
      parts {
        type
        carrier
        from {
          timeLocal
        }
        to {
          timeLocal
        }
      }
      interests {
        name
      }
    }
  }
}
