// flow-typed signature: e478cfb27070af72d4c1196455c1e996
// flow-typed version: <<STUB>>/@kiwicom/orbit-components/lib/Card/CardSection/CardSectionContent_v1.0.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kiwicom/orbit-components/lib/Card/CardSection/CardSectionContent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kiwicom/orbit-components/lib/Card/CardSection/CardSectionContent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@kiwicom/orbit-components/lib/Card/CardSection/CardSectionContent/index' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/Card/CardSection/CardSectionContent'>;
}
declare module '@kiwicom/orbit-components/lib/Card/CardSection/CardSectionContent/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/Card/CardSection/CardSectionContent'>;
}
