// flow-typed signature: 6e7714b0f4ed6c8559c1f61cf3cda714
// flow-typed version: <<STUB>>/@kiwicom/orbit-components/lib/utils/mediaQuery_v1.0.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kiwicom/orbit-components/lib/utils/mediaQuery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kiwicom/orbit-components/lib/utils/mediaQuery' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kiwicom/orbit-components/lib/utils/mediaQuery/consts' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kiwicom/orbit-components/lib/utils/mediaQuery/consts.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/utils/mediaQuery/consts'>;
}
declare module '@kiwicom/orbit-components/lib/utils/mediaQuery/index' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/utils/mediaQuery'>;
}
declare module '@kiwicom/orbit-components/lib/utils/mediaQuery/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/utils/mediaQuery'>;
}
